#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Validar mensaje del commit
echo "🔍 Validando mensaje del commit..."
npx --no -- commitlint --edit $1

echo "✅ Mensaje del commit validado exitosamente!"
